### ISSUE TITLE
Database Issue When Setting Up Extension

### ISSUE THREAD

**Issue by aljawaid** [zomars/bolt-store-hours#6]
I am trying to set up Store HOurs in Bolt 3.4.5 on CentOS PHP7

I add:
```
business:
    name: Businesses
    singular_name: Business
    fields:
        hours:
            type: storehours
```
Then it tells me to update the database, which I do, but when I try to add my business hours, it throws an error.
```
Modifications made to the database:

    Table bolt_business is not the correct schema: invalid column hours, invalid column hours
```

Am I adding the content type (exactly as above) correctly?
